variables:
    H5BENCH_BUILD_PATH: "${CI_PROJECT_DIR}/build"
    H5BENCH_INSTALL_PATH: "${CI_PROJECT_DIR}/install"

stages:
    - build
    - test
    - metrics

build-cori:
    stage: build
    rules:
        - if: '$METRICS == null'
    tags:
        - cori
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
    script:
        - echo "Build h5bench"
        - module swap PrgEnv-intel PrgEnv-gnu 
        - module unload gcc
        - module load cmake gcc/8.3.0
        - module list
        - module load cmake
        - mkdir -p ${H5BENCH_BUILD_PATH}/cori
        - cd ${H5BENCH_BUILD_PATH}/cori
        - cmake ../.. -DCMAKE_INSTALL_PREFIX=${H5BENCH_INSTALL_PATH}/cori -DH5BENCH_ALL=ON
        - make -j 8
        - make install
    artifacts:
        paths:
            - ${H5BENCH_BUILD_PATH}/cori
            - ${H5BENCH_INSTALL_PATH}/cori

build-perlmutter:
    stage: build
    rules:
        - if: '$METRICS == null'
    tags:
        - perlmutter
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        SCHEDULER_PARAMETERS: "--qos=debug -N 1 -t 00:30:00"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
    script:
        - echo "Build h5bench"
        - module list
        - module load cmake
        - mkdir -p ${H5BENCH_BUILD_PATH}/perlmutter
        - cd ${H5BENCH_BUILD_PATH}/perlmutter
        - cmake ../.. -DCMAKE_INSTALL_PREFIX=${H5BENCH_INSTALL_PATH}/perlmutter -DH5BENCH_ALL=ON
        - make -j 8
        - make install
    artifacts:
        paths:
            - ${H5BENCH_BUILD_PATH}/perlmutter
            - ${H5BENCH_INSTALL_PATH}/perlmutter

test-cori:
    stage: test
    rules:
        - if: '$METRICS == null'
    needs: ["build-cori"]
    tags:
        - cori
    variables:
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
        MPICH_MAX_THREAD_SAFETY: "multiple"
    script:
        - echo "Test h5bench SYNC"
        - cd ${H5BENCH_BUILD_PATH}/cori
        - export LD_LIBRARY_PATH=$HDF5_DIR/lib:$LD_LIBRARY_PATH
        - echo "Test h5bench SYNC write/read"
        - python3 ../../samples/update-cori.py ../../samples/sync-write-read-contig-1d-small.json
        - ./h5bench --debug --abort-on-failure --validate-mode ../../samples/sync-write-read-contig-1d-small.json
        - echo "Test h5bench SYNC write unlimited"
        - python3 ../../samples/update-cori.py ../../samples/sync-write-unlimited.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-write-unlimited.json
        - echo "Test h5bench SYNC overwrite"
        - python3 ../../samples/update-cori.py ../../samples/sync-overwrite.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-overwrite.json
        - echo "Test h5bench SYNC append"
        - python3 ../../samples/update-cori.py ../../samples/sync-append.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-append.json
        - echo "Test h5bench SYNC exerciser"
        - python3 ../../samples/update-cori.py ../../samples/sync-exerciser.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-exerciser.json
        - echo "Test h5bench SYNC metadata"
        - python3 ../../samples/update-cori.py ../../samples/sync-metadata.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-metadata.json
        - echo "Test h5bench SYNC amrex"
        - python3 ../../samples/update-cori.py ../../samples/sync-amrex.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-amrex.json
        - echo "Test h5bench SYNC openpmd"
        - python3 ../../samples/update-cori.py ../../samples/sync-openpmd.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-openpmd.json
        
test-perlmutter:
    stage: test
    rules:
        - if: '$METRICS == null'
    needs: ["build-perlmutter"]
    tags:
        - perlmutter
    variables:
        SCHEDULER_PARAMETERS: " -A m2621 --qos=debug --constraint=cpu --tasks-per-node=64 -N 1 -t 00:30:00"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
        MPICH_MAX_THREAD_SAFETY: "multiple"
    script:
        - echo "Test h5bench SYNC"
        - cd ${H5BENCH_BUILD_PATH}/perlmutter
        - export LD_LIBRARY_PATH=$HDF5_DIR/lib:$LD_LIBRARY_PATH
        - echo "Test h5bench SYNC write/read"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-write-read-contig-1d-small.json
        - ./h5bench --debug --abort-on-failure --validate-mode ../../samples/sync-write-read-contig-1d-small.json
        - echo "Test h5bench SYNC write unlimited"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-write-unlimited.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-write-unlimited.json
        - echo "Test h5bench SYNC overwrite"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-overwrite.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-overwrite.json
        - echo "Test h5bench SYNC append"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-append.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-append.json
        - echo "Test h5bench SYNC exerciser"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-exerciser.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-exerciser.json
        - echo "Test h5bench SYNC metadata"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-metadata.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-metadata.json
        - echo "Test h5bench SYNC amrex"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-amrex.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-amrex.json
        - echo "Test h5bench SYNC openpmd"
        - python3 ../../samples/update-perlmutter.py ../../samples/sync-openpmd.json
        - ./h5bench --debug --abort-on-failure ../../samples/sync-openpmd.json

build-cori-metrics:
    stage: build
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule" && $METRICS == "true"'
    tags:
        - cori
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 1 -t 00:30:00 --gres=craynetwork:3"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
    script:
        - echo "Build h5bench"
        - module swap PrgEnv-intel PrgEnv-gnu 
        - module unload gcc
        - module load cmake gcc/8.3.0
        - module list
        - module load cmake
        - mkdir -p ${H5BENCH_BUILD_PATH}/cori-metrics
        - cd ${H5BENCH_BUILD_PATH}/cori-metrics
        - cmake ../.. -DCMAKE_INSTALL_PREFIX=${H5BENCH_INSTALL_PATH}/cori-metrics
        - make -j 8
        - make install
    artifacts:
        paths:
            - ${H5BENCH_BUILD_PATH}/cori-metrics
            - ${H5BENCH_INSTALL_PATH}/cori-metrics

build-perlmutter-metrics:
    stage: build
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule" && $METRICS == "true"'
    tags:
        - perlmutter
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        SCHEDULER_PARAMETERS: "--qos=debug -N 1 -t 00:30:00"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
    script:
        - echo "Build h5bench"
        - module list
        - module load cmake
        - mkdir -p ${H5BENCH_BUILD_PATH}/perlmutter-metrics
        - cd ${H5BENCH_BUILD_PATH}/perlmutter-metrics
        - cmake ../.. -DCMAKE_INSTALL_PREFIX=${H5BENCH_INSTALL_PATH}/perlmutter-metrics
        - make -j 8
        - make install
    artifacts:
        paths:
            - ${H5BENCH_BUILD_PATH}/perlmutter-metrics
            - ${H5BENCH_INSTALL_PATH}/perlmutter-metrics

metrics-cori:
    stage: metrics
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule" && $METRICS == "true"'
    needs: ["build-cori-metrics"]
    tags:
        - cori
    variables:
        SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N 16 -t 00:30:00 --gres=craynetwork:3"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench/hdf5/install"
        MPICH_MAX_THREAD_SAFETY: "multiple"
    script:
        - module load python
        - echo "h5bench SYNC"
        - cd ${H5BENCH_BUILD_PATH}/cori-metrics
        - export LD_LIBRARY_PATH=$HDF5_DIR/lib:$LD_LIBRARY_PATH
        - echo "Run h5bench SYNC write/read"
        - ./h5bench --debug --abort-on-failure --validate-mode ../../samples/metrics-cori.json 2> h5bench-suite-sync.err 1> h5bench-suite-sync.out
        - echo "Install dependencies"
        - pip install pydrive gspread gspread-dataframe google
        - echo "Store h5bench metrics"
        - python3 ../../workflows/store-metrics.py Cori
        - echo "Removing files"
        - rm storage-metrics/*.h5

metrics-perlmutter:
    stage: metrics
    rules:
        - if: '$CI_PIPELINE_SOURCE == "schedule" && $METRICS == "true"'
    needs: ["build-perlmutter-metrics"]
    tags:
        - perlmutter
    variables:
        SCHEDULER_PARAMETERS: " -A m2621 --qos=debug --constraint=cpu --tasks-per-node=64 -N 8 -t 00:30:00"
        HDF5_DIR: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
        HDF5_HOME: "/global/cfs/cdirs/m2621/h5bench-perlmutter/hdf5/install"
        MPICH_MAX_THREAD_SAFETY: "multiple"
    script:
        - module load python
        - module load darshan
        - export LD_PRELOAD="$DARSHAN_BASE_DIR/lib/libdarshan.so"
        - echo "h5bench SYNC"
        - cd ${H5BENCH_BUILD_PATH}/perlmutter-metrics
        - export LD_LIBRARY_PATH=$HDF5_DIR/lib:$LD_LIBRARY_PATH
        - echo "Run h5bench SYNC write/read"
        - ./h5bench --debug --abort-on-failure --validate-mode ../../samples/metrics-perlmutter.json 2> h5bench-suite-sync.err 1> h5bench-suite-sync.out
        - echo "Install dependencies"
        - pip install pydrive gspread gspread-dataframe google
        - echo "Store h5bench metrics"
        - python3 ../../workflows/store-metrics.py Perlmutter
        - echo "Removing files"
        - rm storage-metrics/*.h5
        - export RESULTS="/global/homes/j/jeanbez/h5bench-ci-metrics/perlmutter/$(date +%s)"
        - mkdir -p $RESULTS
        - echo "Fetching Darshan log file"
        - cp /pscratch/darshanlogs/$(date +%Y)/$(date +%-m)/$(date +%u)/*h5bench* ${RESULTS}
        - echo "Fetching runtime files"
        - cp h5bench-suite-sync.err ${RESULTS}
        - cp h5bench-suite-sync.out ${RESULTS}
        - cp -r storage-metrics/* ${RESULTS}
