name: h5bench (HDF5 1.10.4)

on:
  pull_request:

  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-18.04
    container:
      image: jlbez/hdf5-1.10.4
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Dependencies
        run: |
          # PnetCDF
          wget https://parallel-netcdf.github.io/Release/pnetcdf-1.12.2.tar.gz
          tar -zxf pnetcdf-1.12.2.tar.gz
          mv pnetcdf-1.12.2 pnetcdf

      - name: Build PnetCDF
        run: |
          export HDF5_DIR=/opt/hdf5
          export PNETCDF_DIR=/opt/pnetcdf

          cd pnetcdf

          ./configure --prefix=${PNETCDF_DIR} CC=mpicc

          make -j 8
          make install

      - name: Build h5bench
        run: |
          export HDF5_HOME=/opt/hdf5
          export PNETCDF_HOME=/opt/pnetcdf
          
          mkdir build
          cd build
          CC=mpicc cmake ..
          make -j 8
          
      - name: Test h5bench SYNC write/read
        run: |
          cd build
          ./h5bench --debug --abort-on-failure --validate-mode ../samples/sync-write-read-contig-1d-small.json

      - name: Test h5bench SYNC exerciser
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-exerciser.json

      - name: Test h5bench SYNC metadata
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-metadata.json

      - name: Test h5bench SYNC amrex
        run: |
          cd build
          ./h5bench --debug --abort-on-failure ../samples/sync-amrex.json

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/storage/**/std*
          retention-days: 1
