name: h5bench (HDF5 1.10.7)

on:
  pull_request:

  workflow_dispatch:

jobs:
  h5bench:
    runs-on: ubuntu-18.04
    container:
      image: jlbez/hdf5-1.10.4
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Build h5bench
        run: |
          export HDF5_HOME=/opt/hdf5
          mkdir build_sync
          cd build_sync
          CC=mpicc cmake ..
          make -j 8
          
      - name: Test h5bench SYNC write/read
        run: |
          cd build_sync
          ./h5bench --debug --abort-on-failure ../samples/sync-write-read-contig-1d-small.json

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: full-test/*/std*
          retention-days: 1